### ISSUE TITLE
Can not build docker-compose over SSH

### ISSUE THREAD

**Issue by lesha-co** [vx3r/wg-gen-web#106]
docker-compose.yml
```
version: '3.6'
services:
  wg-gen-web-demo:
    image: vx3r/wg-gen-web:latest
    container_name: wg-gen-web-demo
    restart: unless-stopped
    expose:
      - "8080/tcp"
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
      - SMTP_HOST=******
      - SMTP_PORT=25
      - SMTP_USERNAME=******
      - SMTP_PASSWORD=******
      - SMTP_FROM=Wg Gen Web <******>
      # https://github.com/vx3r/wg-gen-web#authentication
      - OAUTH2_PROVIDER_NAME=fake
    volumes:
      - /etc/wireguard:/data
```

output:
```
$ docker-compose up
[+] Running 0/0
 ⠋ wg-gen-web-demo Pulling
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```

... why does it need dbus on the host system?
