### ISSUE TITLE
Error while trying to display stats

### ISSUE THREAD

**Issue by ubenmackin** [vx3r/wg-gen-web#71]
While trying to display stats, I get the following error:

Error: 500 - Internal Server Error: Post "http://172.17.0.1:8182": dial tcp 172.17.0.1:8182: i/o timeout (Client.Timeout exceeded while awaiting headers)

If I try and do a curl from the host, it reruns correctly:

```
ben@vpnserver:/opt/wg-ui$ curl http://172.17.0.1:8182 -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "GetDeviceInfo", "params": {}}'
{"jsonrpc":"2.0","result":{"device":{"name":"wg0","type":"Linux kernel","public_key":"zzzzzzzzzzzzzzzzzzzzzzz=","listen_port":12345,"num_peers":4}},"id":null}
```

Here is my docker-compose.json:

```
version: '3.6'
services:
  wg-ui:
    image: vx3r/wg-gen-web:latest
    container_name: wg-ui
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
      - OAUTH2_PROVIDER_NAME=fake
      - WG_STATS_API=http://172.17.0.1:8182
    volumes:
      - /etc/wireguard:/data
  wg-json-api:
    image: james/wg-api:latest
    container_name: wg-json-api
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    command: wg-api --device wg0 --listen 172.17.0.1:8182

```
