### ISSUE TITLE
Unable to start container via docker-compose

### ISSUE THREAD

**Issue by koonweee** [vx3r/wg-gen-web#80]
Hi, I have been trying to utilize this container via compose, here is my docker-compose.yml snippet:
```
# wg-gen-web - generate and manage wireguard profiles
  wg-gen-web:
    image: vx3r/wg-gen-web
    container_name: wg-gen-web
    restart: always
    environment:
      - WG_CONF_DIR=/data
      - WG_INTERFACE_NAME=wg0.conf
    volumes:
      - /etc/wireguard:/data
```

The container does not start up and constantly reboots instead. Here is the logs pulled from Portainer:
```
standard_init_linux.go:219: exec user process caused: no such file or directory
standard_init_linux.go:219: exec user process caused: no such file or directory
```

I've also tried the docker-compose from the readme and the logs are the same
