### ISSUE TITLE
Ubuntu host, installed Wireguard + tools, wg-gen-web not working

### ISSUE THREAD

**Issue by zilexa** [vx3r/wg-gen-web#86]
I must be missing a step. I used to have PiVPN (Wireguard) installed and created configs with that, everything worked.
Now I uninstalled PiVPN, uninstalled wireguard (which also removes wireguard-tools), deleted `/etc/wireguard`.  

After a reboot,, I do `sudo apt install wireguard` which also installs tools automatically. 
Then run my docker-compose up -d: 
```
  vpn-server-ui:
    image: vx3r/wg-gen-web:latest
    container_name: vpn-server-ui
    restart: always
    networks:
      - management
    environment:
      WG_CONF_DIR: /data
      WG_INTERFACE_NAME: wg0.conf
      SMTP_HOST: $SMTP
      SMTP_PORT: 587
      SMTP_USERNAME: $SMTPUSER
      SMTP_PASSWORD: $SMTPPASS
      SMTP_FROM: $EMAIL
    volumes:
      - /etc/wireguard:/data
    ports:
      - "5100:8080"
```

I can access the webui on port 5100 just fine.

>   Server configuration: 
>   Public Key: ....
>   Listen port: 51822 
>   Server interface addresses: 10.6.6.1/24
> 
>   Client Configuration:
>   Public endpoint: mydomain.cloud:51822
>   DNS server: 1.1.1.1
>   Default allowed: 0.0.0/0, ::/0
>   No values for MTU and keepalive

I create a client:

> email address: my address
> Addresses: 10.6.6.2/32
> Allowed IP addresses: 0.0.0/0, ::/0
> No values for MTU and keepalive

After saving, I do: 
`sudo systemctl start wg-quick@wg0.service` 
Reload doesn't work because wg hasn't been started before. 

Then I scan the QR code with my Android phone and try to connect: nothing. 0 bytes received, some bytes send.

What am I missing?

EDIT: I can access my server LAN IP! Just no internet. Perhaps a DNS issue? 
But I simply used 1.1.1.1 for testing.. would expect that to work.
